apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pp-volitve-2018-zaobljube-enable-cors
spec:
  headers:
    accessControlAllowOriginList:
      - "https://participativni-proracun.djnd.si"
      - "https://participativni-proracun.danesjenovdan.si"
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    accessControlAllowHeaders:
      - "*"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pp-volitve-2018-zaobljube-add-trailing-slash
spec:
  redirectRegex:
    regex: (/2018/zaobljube)(\?.*)?$
    replacement: ${1}/${2}
    permanent: false
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pp-volitve-2018-zaobljube-strip-prefix
spec:
  stripPrefix:
    prefixes:
      - /2018/zaobljube
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pp-volitve-2018-zaobljube
  annotations:
    # do not put cert manager here, root ingress will handle it
    traefik.ingress.kubernetes.io/router.middlewares: |
      pp-kampanja-pp-volitve-2018-zaobljube-enable-cors@kubernetescrd,
      pp-kampanja-pp-volitve-2018-zaobljube-add-trailing-slash@kubernetescrd,
      pp-kampanja-pp-volitve-2018-zaobljube-strip-prefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: participativni-proracun.djnd.si
      http: &http_paths
        paths:
          - path: /2018/zaobljube
            pathType: Prefix
            backend:
              service:
                name: pp-volitve-2018-zaobljube
                port:
                  number: 8801
    - host: participativni-proracun.danesjenovdan.si
      http: *http_paths
