apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pp-kampanja
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: pp-volitve-2022
    newName: rg.fr-par.scw.cloud/djnd/pp-volitve-2022
    newTag: 'd2642fd6a4b4ce8e2b0e7d5fea40adaba4341358'
