apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pp-kampanja
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: pp-preverjamo-2025
    newName: rg.fr-par.scw.cloud/djnd/pp-preverjamo-2025
    newTag: '482f63d6b89a6019272d5eaab45c7985f1146235'
