apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pp-kampanja
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: pp-preverjamo-2025
    newName: rg.fr-par.scw.cloud/djnd/pp-preverjamo-2025
    newTag: '41438563f07338ca025d05bf624301aef9b5ef51'
