name: Build and publish Docker image
on:
  push:
    branches:
      - 'volitve-2022'
jobs:
  push_to_registry:
    name: Build and push Docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Scaleway
        uses: docker/login-action@v1
        with:
          registry: rg.fr-par.scw.cloud/djnd
          username: nologin
          password: ${{ secrets.SCW_SECRET_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            BASE_URL=https://pp2022.lb.djnd.si/
          push: true
          tags: |
            rg.fr-par.scw.cloud/djnd/pp-volitve-2022:${{ github.sha }}
            rg.fr-par.scw.cloud/djnd/pp-volitve-2022:latest

      - name: Update image versions in kustomize/kustomization.yaml
        run: |
          sed -i "s/newTag: .*\+/newTag\: '${{ github.sha }}'/" kustomize/kustomization.yaml

      - name: Commit and push new image versions
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          message: 'Update image versions in kustomize/kustomization.yaml'
